### ISSUE TITLE
Starting a new project

### ISSUE THREAD

**Issue by idkjs** [oxidizing/sihl#147]
How do you start a new `sihl` project? Do we use an `opam` workflow or a npm? In the tutorial you reference various Sihl modules. How are you accessing them?

Generally, it might be worth adding some details until you get the `spin` workflow setup.

Thanks for doing this work and sharing it.

**Comment by jerben** [comment]
Thanks for your interest in the project @idkjs!

At the moment we are working on finalizing the APIs so we haven't invested in documentation. We start to work on a proper getting started story in about 2-3 weeks. With this project we try to bottle an architecture for web apps, so good documentation is just as important as the code.   

Sihl will use `opam` internally, but we will create boilerplate projects/Spin templates for both `opam` and `esy`. So Sihl projects can be done in OCaml or Reason, with either `opam` or `esy`.

At the moment your best bet is to check out the example project https://github.com/oxidizing/sihl-example-issues that uses Sihl, Reason and `opam`. It uses two apps for email and user management. I will update the instructions on how to get it running since it the readme describes steps back when we were using BuckleScript on Node.

**Comment by jerben** [comment]
@idkjs We wrote a short getting started guide: https://github.com/oxidizing/sihl/#getting-started

More to follow, I hope it helps to setup a new project! :)
