### ISSUE TITLE
Integrate app generation with spin

### ISSUE THREAD

**Issue by jerben** [oxidizing/sihl#26]
Create a template: https://github.com/tmattio/spin

**Comment by citizen428** [comment]
Please feel free to ping @tmattio or me if you need help with the template 😃

**Comment by tmattio** [comment]
Hey @jerben, great project, can't wait to build a web app with it!

Since you're planning on building a Spin template, I thought I'd mentioned it could also help you with one the item on your roadmap:
> Scaffolding: The CLI will be extended to allow generating CRUD routes, models, repositories and services quickly

When building a template, you can also provide generators, so users would be able to run:
```
spin gen route
spin gen model
...
```
in a spin-generated Sihl app.

Not sure this will fit your use case, but as @citizen428 mentioned, happy to help if you need anything 🙂

**Comment by jerben** [comment]
Hey @citizen428 @tmattio, thank you for Spin!

Scaffolding is certainly something we want to put into the first release, so we will look into that soon. It makes sense to have a Spin template that creates a Sihl project with a common setup like React, Postgres and User management.

Once we start working on that stuff, I will gladly make use of your offer, thanks! :)

**Comment by jerben** [comment]
Add following default middlewares:

```ocaml
let site () =
  [ Id.middleware
  ; Error.site_middleware
  ; Opium.Middleware.logger
  ; Opium.Middleware.content_length
  ; Opium.Middleware.head
  ; Opium.Middleware.etag
  ; Static.middleware ()
  ; Session.middleware ()
  ; Form.middleware
  ; Csrf.middleware ()
  ; User.session_middleware
  ]
;;

let json_api () =
  [ Id.middleware
  ; Opium.Middleware.logger
  ; Error.json_middleware
  ; Json.middleware
  ; Bearer_token.middleware
  ; User.token_middleware
  ]
;;
```

**Comment by jerben** [comment]
Fixed, initial version: https://github.com/oxidizing/spin-sihl/tree/main/template
